defaults: &defaults
  working_directory: ~/icons
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  build-package:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release to GitHub
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            npm run release-to-github
  publish:
    <<: *defaults
    steps:
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - attach_workspace:
          at: .
      - run:
          name: Publish on npm
          command: npm publish --access=public
  deploy-to-aws:
    docker:
      - image: circleci/python:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Create versioned directory
          command: |
            PACKAGE_VERSION=`python -c "import json; print(json.load(open('package.json'))[u'version'])"`
            mkdir -p versioned/latest
            cp -a dist/. versioned/latest
            mkdir -p versioned/${PACKAGE_VERSION}
            cp -a dist/. versioned/${PACKAGE_VERSION}
      - run:
          name: Deploy versioned directory to S3
          command: |
            export PATH=~/.local/bin:$PATH
            aws s3 sync versioned s3://tw-frontend-assets/icons --acl public-read
  demo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build demo
          command: npm run build-demo
      - run:
          name: Deploy demo
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run deploy-demo

workflows:
  version: 2
  dependencies-test-build-release-and-build-demo:
    jobs:
      - dependencies:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - dependencies
      - build-package:
          requires:
            - dependencies
      - release:
          context: frontend-publish
          requires:
            - test
            - build-package
          filters:
            branches:
              only: master
      - publish:
          context: frontend-publish
          requires:
            - test
            - build-package
          filters:
            branches:
              only: master
      - deploy-to-aws:
          requires:
            - test
            - build-package
          filters:
            branches:
              only: master
      - demo:
          context: frontend-publish
          requires:
            - test
            - build-package
          filters:
            branches:
              only: master